kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

configMapGenerator:
  - name: kibana-dashboards
    files:
      - kibana-dashboard-pa-was.ndjson
      - kibana-dashboard-pa.ndjson
      - kibana-dashboard-pd.ndjson
      - kibana-dashboard-pf-threat.ndjson
      - kibana-dashboard-pf.ndjson

generatorOptions:
 annotations:
   argocd.argoproj.io/sync-options: Replace=true